### ISSUE TITLE
File content

### ISSUE THREAD

**Issue by jcasique** [therecluse26/docuware-php-sdk#1]
Hi, i trying to use your project to connect to Docuware, but file connection.php is missing.

    I think the minimal content is $host, $organization, $username, $password but i can't figure what else.

    Thanks.

**Comment by zkemppel** [comment]
You don't need a connection.php file, you could simply enter the credentials in your initialization of the Platform object:
`$docuware = new Platform('https://domain.com/docuware', 'organization', 'username', 'password');`

If you want a file called connection.php, it would simply look like:
```
<?php
$host = 'https://domain.com/docuware';
$organization 'organization';
$username = 'username';
$password = 'password';
```

**Comment by jcasique** [comment]
> You don't need a connection.php file, you could simply enter the credentials in your initialization of the Platform object:
> `$docuware = new Platform('https://domain.com/docuware', 'organization', 'username', 'password');`
> 
> If you want a file called connection.php, it would simply look like:
> 
> ```
> <?php
> $host = 'https://domain.com/docuware';
> $organization 'organization';
> $username = 'username';
> $password = 'password';
> ```

    By checking the code I could solve.

    Thanks!
