### ISSUE TITLE
Update Select Lists programmatically

### ISSUE THREAD

**Issue by LucasKrmpotic** [therecluse26/docuware-php-sdk#2]
We need to know if it is possible update a Select List programmatically.
Do you have any code example?
Thanks.

**Comment by zkemppel** [comment]
There does not appear to be a REST endpoint to handle this. You may need to look into using the .NET API.
https://developer.docuware.com/dotNet/66b2ed1e-2aef-452a-97cd-5014bbf0242b.html

**Comment by zkemppel** [comment]
![image](https://user-images.githubusercontent.com/13770368/75817504-332eb300-5d65-11ea-8b5b-cf0936085911.png)

I took another look, this might be your best bet, but there isn't any documentation to indicate exactly what it does.
